# Generated by Django 4.1.4 on 2022-12-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_zip_code_to_address'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (name)
            VALUES ('collection1')
        """, """
            DELETE FROM store_collection
            WHERE name = 'collection1'
        """)
    ]
